objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: test-app
    name: wildfly-centos7
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: quay.io/wildfly/wildfly-centos7
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ''
  status:
    dockerImageRepository: ''
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: test-app
    name: test-app
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ''
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: test-app
    name: test-app
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: test-app:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: wildfly-centos7:latest
        incremental: true
        env:
        - name: MYSQL_DATABASE
          value: my_data
        - name: MYSQL_SERVICE_HOST
          valueFrom:
            secretKeyRef:
              name: test-app-database-bind
              key: uri
        - name: MYSQL_SERVICE_PORT
          value: '3306'
        - name: MYSQL_DATASOURCE
          value: MyDS
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: test-app-database-bind
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-app-database-bind
              key: password
        - name: GC_MAX_METASPACE_SIZE
          value: '150'
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      type: Source
    triggers:
    - type: GitHub
      github:
        secret: ${GITHUB_WEBHOOK_SECRET}
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: test-app
    name: test-app
  spec:
    replicas: 1
    selector:
      app: test-app
      deploymentconfig: test-app
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: test-app
          deploymentconfig: test-app
      spec:
        containers:
        - image: test-app:latest
          name: test-app
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources:
            limits:
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 3
          env:
          - name: MYSQL_DATABASE
            value: my_data
          - name: MYSQL_SERVICE_HOST
            valueFrom:
              secretKeyRef:
                name: test-app-database-bind
                key: uri
          - name: MYSQL_SERVICE_PORT
            value: '3306'
          - name: MYSQL_DATASOURCE
            value: MyDS
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: test-app-database-bind
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: test-app-database-bind
                key: password
          - name: GC_MAX_METASPACE_SIZE
            value: '150'
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - test-app
        from:
          kind: ImageStreamTag
          name: test-app:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: test-app
    name: test-app
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: test-app
      deploymentconfig: test-app
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: test-app
    labels:
      app: test-app
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: test-app
- kind: Secret
  apiVersion: v1
  metadata:
    name: test-app-database-bind
    labels:
      app: test-app
  stringData:
    uri: test-app-database
    database: my_data
    user: dbuser
    password: secret
- apiVersion: image.openshift.io/v1
  generation: 0
  image:
    dockerImageLayers: null
    dockerImageMetadata:
      ContainerConfig: {}
      Created: null
      Id: ''
      apiVersion: '1.0'
      kind: DockerImage
    dockerImageMetadataVersion: '1.0'
    metadata:
      creationTimestamp: null
  kind: ImageStreamTag
  lookupPolicy:
    local: false
  metadata:
    creationTimestamp: null
    labels:
      app: test-app
    name: test-app-database:latest
  tag:
    annotations: null
    from:
      kind: DockerImage
      name: 172.30.1.1:5000/openshift/mysql:latest
    generation: null
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ''
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: test-app
    name: test-app-database
  spec:
    replicas: 1
    selector:
      app: test-app
      deploymentconfig: test-app-database
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: test-app
          deploymentconfig: test-app-database
      spec:
        containers:
        - image: 172.30.1.1:5000/openshift/mysql:latest
          name: test-app-database
          ports:
          - containerPort: 3306
            protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
          readinessProbe:
            initialDelaySeconds: 5
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
                -e "SELECT 1"
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 3306
          env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: test-app-database-bind
                key: database
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: test-app-database-bind
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: test-app-database-bind
                key: password
          - name: MYSQL_ROOT_PASSWORD
            value: verysecretrootpassword
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - test-app-database
        from:
          kind: ImageStreamTag
          name: mysql:latest
          namespace: openshift
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: test-app
    name: test-app-database
  spec:
    ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: test-app
      deploymentconfig: test-app-database
  status:
    loadBalancer: {}
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  value: https://github.com/dummy_org/dummy_repo
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: The secret used to configure a GitHub webhook
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
apiVersion: template.openshift.io/v1
kind: Template
